name: Trigger Role Rotation Script

on:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * fri"
jobs:
  rotate:
    name: Rotate weekly roles
    # To not run in forks
    if: github.repository_owner == 'packit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Clone weekly roles
        env:
          TOKEN: ${{ secrets.RELEASEBOT_GITHUB_TOKEN }}
        run: python clone_roles.py
