name: Rebuild docs on merge

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger packit.dev
        uses: peter-evans/repository-dispatch@bf47d102fdb849e755b0b0023ea3e81a44b6f570 # v2
        with:
          token: ${{ secrets.PACKIT_DEV_TOKEN }}
          repository: packit/packit.dev
          event-type: agile-docs-updated
